---
title: "RIF GSEs integrated analysis"
author:
  - Hong Zeng
documentclass: ctexart
keywords:
  - Recurrent implantation failure
  - Robust rank aggregation
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
---

# load data
```{r}
load("data.Rda")
```

# Valcano plot
```{r}
# GSE26787
library(tidyverse)
library(ggrepel)
library(ggplot2)
library(ggpubr)
GSE26787_valcano_df <- GSE26787_res_DEG %>%
  mutate(direction = factor(ifelse(P.Value < 0.05 & abs(logFC) > 1,
                                   ifelse(logFC > 0, "Up", "Down"),"NS"),
                            levels=c('Up','Down','NS'))) %>%
  na.omit()
p_GSE26787 <- ggplot(data = GSE26787_valcano_df, aes(x = logFC, y = -log10(P.Value), colour = direction)) + 
  geom_point(alpha = 0.5, size=0.5) +
  scale_color_manual(values = c("red", "forestgreen", "grey40")) + 
  theme_bw() +
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())+
  theme(legend.title = element_blank(), legend.position = c("none"), text = element_text(size=16, family="serif", face = "bold")) +
  ylab(expression(-log[10]("P Value"))) +
  xlab(expression(log[2]("Fold Change"))) +
  xlim(-4, 4) +
  ylim(0, 5) +
  geom_vline(xintercept = c(-1, 1), 
             lty = 2,
             col = "grey40",
             lwd = 0.6) +
  geom_hline(yintercept = -log10(0.05),
             lty = 2,
             col = "grey40",
             lwd = 0.6)+
  labs(title = "GSE26787")+
  coord_flip()
p_GSE26787
# GSE58144
GSE58144_valcano_df <- GSE58144_res_DEG %>%
        mutate(direction = factor(ifelse(P.Value < 0.05 & abs(logFC) > 1,
                                         ifelse(logFC > 0, "Up", "Down"),"NS"),
                                  levels=c('Up','Down','NS'))) %>%
        na.omit()
p_GSE58144 <- ggplot(data = GSE58144_valcano_df, aes(x = logFC, y = -log10(P.Value), colour = direction)) + 
        geom_point(alpha = 0.5, size=0.5) +
        scale_color_manual(values = c("red", "forestgreen", "grey40")) + 
        theme_bw() +
        theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())+
        theme(legend.title = element_blank(), legend.position = c("none"),text = element_text(size=16, family="serif", face = "bold")) +
        ylab(expression(-log[10]("P Value"))) +
        xlab(expression(log[2]("Fold Change"))) +
        xlim(-6, 6) +
        ylim(0, 210) +
        geom_vline(xintercept = c(-1, 1), 
                   lty = 2,
                   col = "grey40",
                   lwd = 0.6) +
        geom_hline(yintercept = -log10(0.05),
                   lty = 2,
                   col = "grey40",
                   lwd = 0.6)+
        labs(title = "GSE58144")+
        coord_flip()
p_GSE58144

# GSE71331
GS71331_valcano_df <- GSE71331_res_DEG %>%
  mutate(direction = factor(ifelse(P.Value < 0.05 & abs(logFC) > 1,
                                   ifelse(logFC > 0, "Up", "Down"),"NS"),
                            levels=c('Up','Down','NS'))) %>%
  na.omit()
p_GSE71331 <- ggplot(data = GS71331_valcano_df, aes(x = logFC, y = -log10(P.Value), colour = direction)) + 
  geom_point(alpha = 0.5, size=0.5) +
  scale_color_manual(values = c("red", "forestgreen", "grey40")) + 
  theme_bw() +
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())+
  theme(legend.title = element_blank(), legend.position = c("none"), text = element_text(size=16, family="serif", face = "bold")) +
  ylab(expression(-log[10]("P Value"))) +
  xlab(expression(log[2]("Fold Change"))) +
  xlim(-4, 4) +
  ylim(0, 5) +
  geom_vline(xintercept = c(-1, 1), 
             lty = 2,
             col = "grey40",
             lwd = 0.6) +
  geom_hline(yintercept = -log10(0.05),
             lty = 2,
             col = "grey40",
             lwd = 0.6)+
  labs(title = "GSE71331")+
  coord_flip()
p_GSE71331

# GSE92324
GS92324_valcano_df <- GSE92324_res_DEG %>%
  mutate(direction = factor(ifelse(P.Value < 0.05 & abs(logFC) > 1,
                                   ifelse(logFC > 0, "Up", "Down"),"NS"),
                            levels=c('Up','Down','NS'))) %>%
  na.omit()
p_GSE92324 <- ggplot(data = GS92324_valcano_df, aes(x = logFC, y = -log10(P.Value), colour = direction)) + 
  geom_point(alpha = 0.5, size=0.5) +
  scale_color_manual(values = c("red", "forestgreen", "grey40")) + 
  theme_bw() +
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())+
  theme(legend.title = element_blank(), legend.position = c("none"), text = element_text(size=16, family="serif", face = "bold")) +
  ylab(expression(-log[10]("P Value"))) +
  xlab(expression(log[2]("Fold Change"))) +
  xlim(-5, 5) +
  ylim(0, 13) +
  geom_vline(xintercept = c(-1, 1), 
             lty = 2,
             col = "grey40",
             lwd = 0.6) +
  geom_hline(yintercept = -log10(0.05),
             lty = 2,
             col = "grey40",
             lwd = 0.6)+
  labs(title = "GSE92324")+
  coord_flip()
p_GSE92324
```


# RRA
```{r}
library(tidyverse)
GSE26787_res_DEG <- arrange(GSE26787_res_DEG, P.Value, abs(logFC))
GSE58144_res_DEG <- arrange(GSE58144_res_DEG, P.Value, abs(logFC))
GSE92324_res_DEG <- arrange(GSE92324_res_DEG, P.Value, abs(logFC))
GSE71331_res_DEG <- arrange(GSE71331_res_DEG, P.Value, abs(logFC))
GSE111974_res_DEG <- arrange(GSE111974_res_DEG, P.Value, abs(logFC))
GSEs <- c("GSE26787", 
          "GSE58144", 
          "GSE92324",
          "GSE71331")
intersect <- intersect(intersect(intersect(intersect(GSE111974_res_DEG$symbol, GSE71331_res_DEG$symbol), GSE26787_res_DEG$symbol), GSE92324_res_DEG$symbol), GSE58144_res_DEG$symbol)
GSE26787_res_DEG <- GSE26787_res_DEG %>% filter(symbol %in% intersect)
GSE58144_res_DEG <- GSE58144_res_DEG %>% filter(symbol %in% intersect)
GSE92324_res_DEG <- GSE92324_res_DEG %>% filter(symbol %in% intersect)
GSE71331_res_DEG <- GSE71331_res_DEG %>% filter(symbol %in% intersect)
GSE111974_res_DEG <- GSE111974_res_DEG %>% filter(symbol %in% intersect)
library(RobustRankAggreg)
# RRA analysis
library(tidyverse)
glist_up <- list()
glist_down <- list()
for(i in 1:4){
  glist_up[[i]] <- get(paste0(GSEs[i],"_res_DEG")) %>% filter(logFC > 0) %>% .[[1]]
  glist_down[[i]] <- get(paste0(GSEs[i],"_res_DEG")) %>% filter(logFC < 0 ) %>% .[[1]]
}
res_RRA_up <- aggregateRanks(glist_up, method = "RRA", full = T, exact = T)#aggregateRanks
res_RRA_down <- aggregateRanks(glist_down, method = "RRA", full = T, exact = T)
all_signi_result1 <- bind_rows(res_RRA_up %>% mutate(direction = "up"), 
                              res_RRA_down %>% mutate(direction = "down")) %>%
  filter(Score < 0.05) %>% 
  rownames_to_column(var = "SYMBOL") %>% arrange(Score)
all_signi_result2 <- bind_rows(res_RRA_up %>% mutate(direction = "up"), 
                              res_RRA_down %>% mutate(direction = "down")) %>%
  filter(Score < 0.01) %>% 
  rownames_to_column(var = "SYMBOL")  %>% arrange(Score)

#Heatmap of top25 up-regulated and down-regulated genes
top25_up <- res_RRA_up %>% 
  mutate(across(.fn = as.character)) %>% 
  dplyr::slice(1:25) %>%
  .[[1]] 
top25_down <- res_RRA_down %>% 
  mutate(across(.fn = as.character)) %>% 
  dplyr::slice(1:25) %>% 
  .[[1]] 
top50 <- c(top25_up, top25_down)
heatmap_list <- list()
for(i in 1:4) {
  heatmap_list[[i]] <- get(paste0(GSEs[i], "_res_DEG")) %>%
    dplyr::select(1, 2) %>%
    dplyr::filter(symbol %in% top50) %>% 
    mutate(GSE = GSEs[i])
}
heatmap_df <- bind_rows(heatmap_list) %>% 
  pivot_wider(names_from = GSE, values_from = logFC) %>% 
  mutate(symbol = factor(symbol, levels = top50)) %>% 
  arrange(symbol) %>% 
  column_to_rownames(var = "symbol")
head(heatmap_df)
library(pheatmap)
pheatmap::pheatmap(mat = heatmap_df,
                   color = colorRampPalette(c("blue", "white","red"))(500),
                   cluster_rows = F,
                   cluster_cols = F,
                   display_numbers = T,
                   fontsize=12,
                   fontsize_row=9,
                   angle_col = "45"
)
PPI_genelist <- all_signi_result2$SYMBOL
write.table(PPI_genelist, "PPI_input.txt", row.names = F, col.names = F, quote = F)
```

# GO and KEGG enrichment analysis
```{r}
#BiocManager::install("clusterProfiler")
#BiocManager::install("org.Hs.eg.db")
library(clusterProfiler)
library(org.Hs.eg.db)
library(tidyverse)
input <- all_signi_result1
head(input)
# Convert Gene Symbol to Entriz ID
gene.df <- bitr(input$SYMBOL,
                fromType = "SYMBOL",
                toType = c("ENSEMBL", "ENTREZID"),
                OrgDb = org.Hs.eg.db)
gene <- gene.df$ENTREZID
#GO enrichment
ego_MF <- enrichGO(gene = gene,
                OrgDb = org.Hs.eg.db, 
                pvalueCutoff =0.05, 
                ont = "MF",
                readable = TRUE)
ego_MF <- ego_MF@result
head(ego_MF,10)
ego_BP <- enrichGO(gene = gene,
                OrgDb = org.Hs.eg.db, 
                pvalueCutoff =0.05, 
                ont = "BP",
                readable = TRUE)
ego_BP <- ego_BP@result
head(ego_BP,10)
ego_CC <- enrichGO(gene = gene,
                OrgDb = org.Hs.eg.db, 
                pvalueCutoff =0.05, 
                qvalueCutoff =0.05,
                ont = "CC",
                readable = TRUE)
ego_CC <- ego_CC@result
head(ego_CC, 10)
#KEGG enrichment
kk <- enrichKEGG(gene = gene, 
                 organism = "hsa", 
                 pvalueCutoff =0.05, 
                 qvalueCutoff = 0.2)
kk <- kk@result
head(kk, 10)
# write GO results
write.table(ego_MF[ego_MF$pvalue<0.05, ],file="GO_MFresult.txt",sep="\t",
            quote=F,row.names = F)
write.table(ego_CC[ego_CC$pvalue<0.05, ],file="GO_CCresult.txt",sep="\t",
            quote=F,row.names = F)
write.table(ego_BP[ego_BP$pvalue<0.05, ],file="GO_BPresult.txt",sep="\t",
            quote=F,row.names = F)
write.table(kk[kk$pvalue<0.05, ],file="KEGG_result.txt",sep="\t",
            quote=F,row.names = F)
#Enrichment plot
kk$ONTOLOGY <- c("KEGG")
ego_BP$ONTOLOGY <- c("BP")
ego_CC$ONTOLOGY <- c("CC")
ego_MF$ONTOLOGY <- c("MF")
enrich <- bind_rows(kk[c(1:10),], ego_BP[c(1:10),], ego_CC[c(1:10),], ego_MF[c(1:10),])
enrich$ONTOLOGY <- factor(enrich$ONTOLOGY, levels = c("BP", "MF", "CC", "KEGG"))
enrich <- enrich %>% arrange(desc(ONTOLOGY), desc(pvalue))
y <- factor(enrich$Description, levels = enrich$Description)
ggplot(enrich,aes(pvalue, y))+
  geom_point(aes(size=Count,shape=ONTOLOGY,color=-1*log10(pvalue)))+
  scale_color_gradient(low="green",high = "red")+
  labs(color=expression(-log[10](pvalue)),size="Count")+
  theme_bw()+
  ylab("")
```

# Find key hub genes
```{r}
library(tidyverse)
cytohubba <- read_csv("cytohubba.csv")
cytohubba_MCC <- cytohubba %>% arrange(desc(MCC))
cytohubba_DMNC <- cytohubba %>% arrange(desc(DMNC))
cytohubba_Degree <- cytohubba %>% arrange(desc(Degree))
cytohubba_EPC <- cytohubba %>% arrange(desc(EPC))
key_hubgene <- intersect(intersect(intersect(intersect(cytohubba_MCC[1:100, ]$node_name, cytohubba_DMNC[1:100, ]$node_name), cytohubba_Degree[1:100, ]$node_name), cytohubba_EPC[1:100, ]$node_name), all_signi_result2[1:100, ]$SYMBOL)
key_hubgene
```

#Visualization of intersection of too100 robust DEGs and too100 hubgenes follwing different methods by Venn diagram
```{r}
library(VennDiagram)
library(RColorBrewer)
venn.diagram(x = list("DEG" = all_signi_result2[1:100, ]$SYMBOL, 
                      "MCC" = cytohubba_MCC$node_name,
                      "DMNC" = cytohubba_DMNC$node_name,
                      "Degree" = cytohubba_Degree$node_name,
                      "EPC" = cytohubba_EPC$node_name),
             imagetype="tiff",
             filename = "venn plot.tiff",
             fill = brewer.pal(5,"Set3"),
             scaled = T,
             cex = 1.5,
             cat.cex = 1.5,
             col="grey",
             main = "",
             main.cex = 2)
```

# Robust DEGS and hub genes expression validation
```{r}
# Validation gene list
validate_genes <- key_hubgene
validata_data <- t(GSE111974_expr_anno)
validata_data <- validata_data %>% as.data.frame() %>% rownames_to_column("sample_id") %>%
  left_join(Targets_GSE111974[, c("sample_id", "group")], by="sample_id")
validata_data <- validata_data %>% dplyr::select(sample_id, group, all_of(validate_genes))
validata_data <- within(validata_data, {
  group <- gsub(group, pattern = "con", replacement = "Control") 
  group <- gsub(group, pattern = "IF", replacement = "RIF")
})
# Statistical table of validated genes in GSE111974
library(compareGroups)
table1 <- compareGroups::descrTable(group~.- sample_id, data=validata_data, digits = 2, method = "2")
table1
export2word(table1, file="validation_table_GSE111974.docx")
# voilin plot showing the significantly different hub genes in GSE111974
library(ggpubr)
voilin_list <- data.frame(table1$descr) %>% filter(p.overall < 0.05) %>% rownames()
for (i in voilin_list) {
        pdf(file = paste0(i, ".pdf"),width = 4,height =4.5)
        print(ggviolin(validata_data, x = "group", y = i,
                              fill = "group",
                              add = 'boxplot',
                              add.params = list(fill = 'white'),
                              palette = c("cornflowerblue","pink"), 
                              xlab = "GSE111974",
                              ylab = paste0("Normalized expression of ", i),
                              trim = T,
                              alpha = 0.8,
                              width = 1,
                              ggtheme = theme_bw())+
  stat_compare_means(method = "wilcox.test")+
  theme(text = element_text(size=18, color = "black"),
        legend.title=element_blank(),axis.text = element_text(size=18, color = "black"),
        panel.grid.major=element_blank(),panel.grid.minor=element_blank(),
        legend.position = c("top")))
        dev.off()
}
```


# Predictive model
```{r}
# build a predictive model using the significant different hub genes
validata_data <- column_to_rownames(validata_data, var = "sample_id")
validata_data$group <- factor(validata_data$group, levels = c("Control", "RIF"))
set.seed(1234)
train <- sample(nrow(validata_data), 0.6*nrow(validata_data))
df.train <- validata_data[train,]
df.validate <- validata_data[-train,]
table(df.train$group)
table(df.validate$group)
fit.logit <- glm(group~SQLE+LAMC1+HOXB4+PIP5K1B+PAX2+ALDH6A1+SALL1+EYA1+TAGLN+ST6GALNAC1, data=df.train, family=binomial())
summary(fit.logit)
prob_train <- predict(fit.logit, df.train) 
logit.train <- factor(prob_train > .5, levels=c(FALSE, TRUE),          
                     labels=c("Control", "RIF")) 
logit.perf_train <- table(df.train$group, logit.train,
                    dnn=c("Actual", "Predicted")) 
logit.perf_train
# Validate in the validated data
prob_pred <- predict(fit.logit, df.validate)
logit.pred <- factor(prob_pred > .5, levels=c(FALSE, TRUE),          
                     labels=c("Control", "RIF")) 
logit.perf_validate <- table(df.validate$group, logit.pred,
                    dnn=c("Actual", "Predicted")) 
logit.perf_validate
acuracy_rate <- (logit.perf_validate[1]+logit.perf_validate[4])/sum(logit.perf_validate)
acuracy_rate
# draw ROC of the validate data
library(pROC)
pre <- predict(fit.logit, df.validate)
modelroc <- roc(df.validate$group, pre)
plot(modelroc, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),
     grid.col=c("green", "red"), max.auc.polygon=TRUE,
     auc.polygon.col="skyblue", print.thres="best")
roc.data <- data.frame(
  thresholds = modelroc$thresholds,
  sensitivity = modelroc$sensitivities,
  specificity = modelroc$specificities
)
```

